### ISSUE TITLE
Outdated orientation in using-flex-layout.md (left to right)

### ISSUE THREAD

**Issue by ricardo7634234** [vtex-apps/io-documentation#418]
Can you check the file https://github.com/vtex-apps/io-documentation/blob/master/docs/en/Recipes/layout/using-flex-layout.md?

I believe that the text could be improved.

FROM:
The flex-layout.col#text-about-us block is going to display its child dependencies in an interface, from left to right, one after the other.

TO:
The flex-layout.col#text-about-us block is going to display its child dependencies in an interface, from top to bottom, one after the other.

**Comment by guerreirobeatriz** [comment]
Fixed.
